# Header
menu:
  # 主页: /
  所有文章: /archives
  技术思考: /categories/IT技术/
  生活随笔: /categories/随笔/
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/tenstone"
  weibo: "http://weibo.com/511231870"
  zhihu: "http://www.zhihu.com/people/lyc90"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: true

# Miscellaneous
google_analytics: 'UA-70840406-1'
favicon: /favicon.png

#你的头像url
avatar: http://tenstone.me/images/avatar.jpg
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: tenstone
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: true
#开启——
friends:
  安正超的博客: http://overtrue.me/
  朱业峰的博客: http://www.knowledgeway.cn/

#是否开启“关于我”。
#不开启——
aboutme: true
#开启——
aboutme: 风一样的男人